// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/proto.proto

package proto_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestTClient is the client API for TestT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestTClient interface {
	TestA(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type testTClient struct {
	cc grpc.ClientConnInterface
}

func NewTestTClient(cc grpc.ClientConnInterface) TestTClient {
	return &testTClient{cc}
}

func (c *testTClient) TestA(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/PEER2PEER.testT/testA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestTServer is the server API for TestT service.
// All implementations must embed UnimplementedTestTServer
// for forward compatibility
type TestTServer interface {
	TestA(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedTestTServer()
}

// UnimplementedTestTServer must be embedded to have forward compatible implementations.
type UnimplementedTestTServer struct {
}

func (UnimplementedTestTServer) TestA(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestA not implemented")
}
func (UnimplementedTestTServer) mustEmbedUnimplementedTestTServer() {}

// UnsafeTestTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestTServer will
// result in compilation errors.
type UnsafeTestTServer interface {
	mustEmbedUnimplementedTestTServer()
}

func RegisterTestTServer(s grpc.ServiceRegistrar, srv TestTServer) {
	s.RegisterService(&TestT_ServiceDesc, srv)
}

func _TestT_TestA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestTServer).TestA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PEER2PEER.testT/testA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestTServer).TestA(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// TestT_ServiceDesc is the grpc.ServiceDesc for TestT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PEER2PEER.testT",
	HandlerType: (*TestTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "testA",
			Handler:    _TestT_TestA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
